services:
  ares-db:
    image: postgres:15
    container_name: ares_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ares_password
      POSTGRES_DB: ares_db
    ports:
      - "5432:5432"
    volumes:
      - ares_pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  ares-cache:
    image: redis:7
    container_name: ares_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: ares_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - DB_PASSWORD=ares_password
      - DB_HOST=ares_postgres
      - REDIS_HOST=ares_redis
    depends_on:
      - ares-db
      - ares-cache

  frontend:
    build: ./frontend
    container_name: ares_frontend
    ports:
      - "80:80"

volumes:
  ares_pg_data: